Updates

diff --git a/.github/workflows/homebrew.yaml b/.github/workflows/homebrew.yaml
--- a/.github/workflows/homebrew.yaml
+++ b/.github/workflows/homebrew.yaml
@@ -32,27 +32,15 @@ jobs:
           url: "https://pypi.org/pypi/${{ inputs.name }}/${{ inputs.version }}/json"
           path: '$.urls[?(@.packagetype=="sdist")]'
 
-      - name: "Validate Outputs"
-        uses: cssnr/validate-outputs-action@master
-        with:
-          outputs: ${{ toJSON(steps.url.outputs) }}
-          data: |
-            url:
-            sha256:
-
-      #- name: "Verify URL"
-      #  env:
-      #    url: ${{ fromJSON(steps.url.outputs.result).url }}
-      #    sha256: ${{ fromJSON(steps.url.outputs.result).digests.sha256 }}
-      #  run: |
-      #    echo "download-url: ${url}"
-      #    echo "download-sha256: ${sha256}"
-      #    if [ -z "${url}" ];then
-      #      echo "Missing URL" && exit 1
-      #    fi
-      #    if [ -z "${sha256}" ];then
-      #      echo "Missing SHA256" && exit 1
-      #    fi
+      - name: "Verify URL"
+        env:
+          url: ${{ fromJSON(steps.url.outputs.result).url }}
+          sha256: ${{ fromJSON(steps.url.outputs.result).digests.sha256 }}
+        run: |
+          echo "url: ${url}"
+          echo "sha256: ${sha256}"
+          [ -z "${url}" ] && echo "Missing URL" && exit 1
+          [ -z "${sha256}" ] && echo "Missing SHA256" && exit 1
 
       - name: "Homebrew Action"
         id: homebrew
